# Generated by Django 5.0.3 on 2025-11-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='secure_uploads/{instance.album.uid}/{uuid.uuid4()}_{filename}'),
        ),
    ]
