# Generated by Django 5.0.3 on 2025-11-04 00:52

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to=gallery.models.private_upload_path),
        ),
    ]
