# Generated by Django 5.0.3 on 2025-11-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_sharedlink_temporaryuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedlink',
            name='passphrase_raw',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
